#!/bin/bash

NAME="ticket_app"
DIR=/home/ubuntu/ticket_system
USER=ubuntu
GROUP=ubuntu
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
MODULE=main:app

echo "Starting $NAME"

cd $DIR
source venv/bin/activate

exec gunicorn ${MODULE} \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind 0.0.0.0:8000 \
  --log-level=debug \
  --log-file=-
